credentials:
  usernames:
    admin:
      email: aeonthings@gmail.com
      name: admin
      password: $2b$12$AumEn4Ow3kmQpLtxqemiEOiuN4rrHPCL3IdUHxr/Jy76N0C7/FzVO
    test_user:
      email: test@gmail.com
      name: Testing Guy
      password: edf

cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name

preauthorized:
  emails:
  - praloumi@gmail.com
