credentials:
  usernames:
    admin:
      email: aeonthings@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: admin
      password: $2b$12$URTz11NxRZQFF.GktCNkX.L7Gxfbqq3tO.S44T3WpYtQ3JxIJRwgi
    test_user:
      email: test@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Testing Guy
      password: $2b$12$WX5kjbwO9P6DgYqcFgnls.Q0JQqFQKbrYwIebtzyTSP0PwycD898K

cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name

preauthorized:
  emails:
  - praloumi@gmail.com
