credentials:
  usernames:
    admin:
      email: aeonthings@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: admin
      password: Azerty_94400
    test_user:
      email: test@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Testing Guy
      password: Azerty_94

cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
  
preauthorized:
  emails:
  - praloumi@gmail.com
