credentials:
  usernames:
    admin:
      email: aeonthings@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: admin
      password: $2b$12$Bb4OvTNJw1IDMcTmHYgViOC52eaQX.BfPjRiWcYmcOVWmdzNOSN3W
    test_user:
      email: test@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Testing Guy
      password: $2b$12$5J.eWbV0RTdqIUUP4bX8F.dDjqnXURaii.BgrM8pgTupnz0Kpp4Iu

cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name

preauthorized:
  emails:
  - praloumi@gmail.com
