cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    admin:
      email: aeonthings@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: admin
      password: pbkdf2:sha256:600000$hj89sDg2XMTbKyvW$edcb00d62506c84709ac6a24ccbcb81115b1b9932e9485e74683604888c664c2
    test_user:
      email: test@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Testing Guy
      password: pbkdf2:sha256:600000$OfYd5h3B8cIlEneu$1b07e0573a3ae3f0df7c903040c6e3fcfbdb8129f1a9f0cecb2e4c126482d1b1
preauthorized:
  emails:
  - praloumi@gmail.com
