credentials:
  usernames:
    amir:
      email: aeonthings@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Amir
      password: Gdze_94400 # Will be hashed automatically
    SiiX:
      email: s@siix.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: The one and only "SiiX"
      password: R4PBKrvsDdMe-.RDr6jFgajXBNd9e # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
  - praloumi@gmail.com