credentials:
  usernames:
    admin:
      email: aeonthings@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: admin
      password: $2b$12$glO.BLWwHbEflojRSomLnO1JKe.8wxWbi/KZIZe2Rj7Kpj5NOHFmm
    test_user:
      email: test@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Testing Guy
      password: $2b$12$u917eht94cO8.8syC9FRuuurBZ0N.Zd86ryEE5ObV7fQm2Ns2dynO

cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name

preauthorized:
  emails:
  - praloumi@gmail.com
