version: '3.8'

services:
  streamlit:
    build: .
    container_name: nocodeml_streamlit
    ports:
      - "8501:8501"
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nocodeml_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - streamlit
    networks:
      - webnet

networks:
  webnet:

