version: '3'
services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    networks:
      - nocode_ml_network
    container_name: streamlit_container

networks:
  nocode_ml_network:
    driver: bridge

